// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// phaseR_nuts_sampler
List phaseR_nuts_sampler(List data, NumericVector init, int n_iter, int n_warmup, int n_trans_coef, int n_dyn_coef_0, int n_dyn_coef_1, double target_accept, int max_treedepth);
RcppExport SEXP _phaseR_phaseR_nuts_sampler(SEXP dataSEXP, SEXP initSEXP, SEXP n_iterSEXP, SEXP n_warmupSEXP, SEXP n_trans_coefSEXP, SEXP n_dyn_coef_0SEXP, SEXP n_dyn_coef_1SEXP, SEXP target_acceptSEXP, SEXP max_treedepthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type init(initSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type n_warmup(n_warmupSEXP);
    Rcpp::traits::input_parameter< int >::type n_trans_coef(n_trans_coefSEXP);
    Rcpp::traits::input_parameter< int >::type n_dyn_coef_0(n_dyn_coef_0SEXP);
    Rcpp::traits::input_parameter< int >::type n_dyn_coef_1(n_dyn_coef_1SEXP);
    Rcpp::traits::input_parameter< double >::type target_accept(target_acceptSEXP);
    Rcpp::traits::input_parameter< int >::type max_treedepth(max_treedepthSEXP);
    rcpp_result_gen = Rcpp::wrap(phaseR_nuts_sampler(data, init, n_iter, n_warmup, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, target_accept, max_treedepth));
    return rcpp_result_gen;
END_RCPP
}
// phaseR_nuts_sampler_re
List phaseR_nuts_sampler_re(List data, NumericVector init, int n_iter, int n_warmup, int n_trans_coef, int n_dyn_coef_0, int n_dyn_coef_1, int n_trans_re, int n_dyn_re_0, int n_dyn_re_1, bool has_trans_re, bool has_dyn_re_0, bool has_dyn_re_1, double target_accept, int max_treedepth);
RcppExport SEXP _phaseR_phaseR_nuts_sampler_re(SEXP dataSEXP, SEXP initSEXP, SEXP n_iterSEXP, SEXP n_warmupSEXP, SEXP n_trans_coefSEXP, SEXP n_dyn_coef_0SEXP, SEXP n_dyn_coef_1SEXP, SEXP n_trans_reSEXP, SEXP n_dyn_re_0SEXP, SEXP n_dyn_re_1SEXP, SEXP has_trans_reSEXP, SEXP has_dyn_re_0SEXP, SEXP has_dyn_re_1SEXP, SEXP target_acceptSEXP, SEXP max_treedepthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type init(initSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type n_warmup(n_warmupSEXP);
    Rcpp::traits::input_parameter< int >::type n_trans_coef(n_trans_coefSEXP);
    Rcpp::traits::input_parameter< int >::type n_dyn_coef_0(n_dyn_coef_0SEXP);
    Rcpp::traits::input_parameter< int >::type n_dyn_coef_1(n_dyn_coef_1SEXP);
    Rcpp::traits::input_parameter< int >::type n_trans_re(n_trans_reSEXP);
    Rcpp::traits::input_parameter< int >::type n_dyn_re_0(n_dyn_re_0SEXP);
    Rcpp::traits::input_parameter< int >::type n_dyn_re_1(n_dyn_re_1SEXP);
    Rcpp::traits::input_parameter< bool >::type has_trans_re(has_trans_reSEXP);
    Rcpp::traits::input_parameter< bool >::type has_dyn_re_0(has_dyn_re_0SEXP);
    Rcpp::traits::input_parameter< bool >::type has_dyn_re_1(has_dyn_re_1SEXP);
    Rcpp::traits::input_parameter< double >::type target_accept(target_acceptSEXP);
    Rcpp::traits::input_parameter< int >::type max_treedepth(max_treedepthSEXP);
    rcpp_result_gen = Rcpp::wrap(phaseR_nuts_sampler_re(data, init, n_iter, n_warmup, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, n_trans_re, n_dyn_re_0, n_dyn_re_1, has_trans_re, has_dyn_re_0, has_dyn_re_1, target_accept, max_treedepth));
    return rcpp_result_gen;
END_RCPP
}
// phaseR_nuts_sampler_k
List phaseR_nuts_sampler_k(List data, NumericVector init, int n_iter, int n_warmup, IntegerVector n_dyn_coef, IntegerVector n_trans_coef, int k_phases, double target_accept, int max_treedepth);
RcppExport SEXP _phaseR_phaseR_nuts_sampler_k(SEXP dataSEXP, SEXP initSEXP, SEXP n_iterSEXP, SEXP n_warmupSEXP, SEXP n_dyn_coefSEXP, SEXP n_trans_coefSEXP, SEXP k_phasesSEXP, SEXP target_acceptSEXP, SEXP max_treedepthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type init(initSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type n_warmup(n_warmupSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n_dyn_coef(n_dyn_coefSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n_trans_coef(n_trans_coefSEXP);
    Rcpp::traits::input_parameter< int >::type k_phases(k_phasesSEXP);
    Rcpp::traits::input_parameter< double >::type target_accept(target_acceptSEXP);
    Rcpp::traits::input_parameter< int >::type max_treedepth(max_treedepthSEXP);
    rcpp_result_gen = Rcpp::wrap(phaseR_nuts_sampler_k(data, init, n_iter, n_warmup, n_dyn_coef, n_trans_coef, k_phases, target_accept, max_treedepth));
    return rcpp_result_gen;
END_RCPP
}
// phase_log_likelihood
double phase_log_likelihood(NumericVector params, List data, int n_trans_coef, int n_dyn_coef_0, int n_dyn_coef_1);
RcppExport SEXP _phaseR_phase_log_likelihood(SEXP paramsSEXP, SEXP dataSEXP, SEXP n_trans_coefSEXP, SEXP n_dyn_coef_0SEXP, SEXP n_dyn_coef_1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type n_trans_coef(n_trans_coefSEXP);
    Rcpp::traits::input_parameter< int >::type n_dyn_coef_0(n_dyn_coef_0SEXP);
    Rcpp::traits::input_parameter< int >::type n_dyn_coef_1(n_dyn_coef_1SEXP);
    rcpp_result_gen = Rcpp::wrap(phase_log_likelihood(params, data, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1));
    return rcpp_result_gen;
END_RCPP
}
// phase_log_prior
double phase_log_prior(NumericVector params, int n_trans_coef, int n_dyn_coef_0, int n_dyn_coef_1);
RcppExport SEXP _phaseR_phase_log_prior(SEXP paramsSEXP, SEXP n_trans_coefSEXP, SEXP n_dyn_coef_0SEXP, SEXP n_dyn_coef_1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< int >::type n_trans_coef(n_trans_coefSEXP);
    Rcpp::traits::input_parameter< int >::type n_dyn_coef_0(n_dyn_coef_0SEXP);
    Rcpp::traits::input_parameter< int >::type n_dyn_coef_1(n_dyn_coef_1SEXP);
    rcpp_result_gen = Rcpp::wrap(phase_log_prior(params, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1));
    return rcpp_result_gen;
END_RCPP
}
// phase_log_posterior
double phase_log_posterior(NumericVector params, List data, int n_trans_coef, int n_dyn_coef_0, int n_dyn_coef_1);
RcppExport SEXP _phaseR_phase_log_posterior(SEXP paramsSEXP, SEXP dataSEXP, SEXP n_trans_coefSEXP, SEXP n_dyn_coef_0SEXP, SEXP n_dyn_coef_1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type n_trans_coef(n_trans_coefSEXP);
    Rcpp::traits::input_parameter< int >::type n_dyn_coef_0(n_dyn_coef_0SEXP);
    Rcpp::traits::input_parameter< int >::type n_dyn_coef_1(n_dyn_coef_1SEXP);
    rcpp_result_gen = Rcpp::wrap(phase_log_posterior(params, data, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1));
    return rcpp_result_gen;
END_RCPP
}
// phase_log_likelihood_re
double phase_log_likelihood_re(NumericVector params, List data, int n_trans_coef, int n_dyn_coef_0, int n_dyn_coef_1, int n_trans_re, int n_dyn_re_0, int n_dyn_re_1, bool has_trans_re, bool has_dyn_re_0, bool has_dyn_re_1);
RcppExport SEXP _phaseR_phase_log_likelihood_re(SEXP paramsSEXP, SEXP dataSEXP, SEXP n_trans_coefSEXP, SEXP n_dyn_coef_0SEXP, SEXP n_dyn_coef_1SEXP, SEXP n_trans_reSEXP, SEXP n_dyn_re_0SEXP, SEXP n_dyn_re_1SEXP, SEXP has_trans_reSEXP, SEXP has_dyn_re_0SEXP, SEXP has_dyn_re_1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type n_trans_coef(n_trans_coefSEXP);
    Rcpp::traits::input_parameter< int >::type n_dyn_coef_0(n_dyn_coef_0SEXP);
    Rcpp::traits::input_parameter< int >::type n_dyn_coef_1(n_dyn_coef_1SEXP);
    Rcpp::traits::input_parameter< int >::type n_trans_re(n_trans_reSEXP);
    Rcpp::traits::input_parameter< int >::type n_dyn_re_0(n_dyn_re_0SEXP);
    Rcpp::traits::input_parameter< int >::type n_dyn_re_1(n_dyn_re_1SEXP);
    Rcpp::traits::input_parameter< bool >::type has_trans_re(has_trans_reSEXP);
    Rcpp::traits::input_parameter< bool >::type has_dyn_re_0(has_dyn_re_0SEXP);
    Rcpp::traits::input_parameter< bool >::type has_dyn_re_1(has_dyn_re_1SEXP);
    rcpp_result_gen = Rcpp::wrap(phase_log_likelihood_re(params, data, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, n_trans_re, n_dyn_re_0, n_dyn_re_1, has_trans_re, has_dyn_re_0, has_dyn_re_1));
    return rcpp_result_gen;
END_RCPP
}
// phase_log_prior_re
double phase_log_prior_re(NumericVector params, int n_trans_coef, int n_dyn_coef_0, int n_dyn_coef_1, int n_trans_re, int n_dyn_re_0, int n_dyn_re_1, bool has_trans_re, bool has_dyn_re_0, bool has_dyn_re_1);
RcppExport SEXP _phaseR_phase_log_prior_re(SEXP paramsSEXP, SEXP n_trans_coefSEXP, SEXP n_dyn_coef_0SEXP, SEXP n_dyn_coef_1SEXP, SEXP n_trans_reSEXP, SEXP n_dyn_re_0SEXP, SEXP n_dyn_re_1SEXP, SEXP has_trans_reSEXP, SEXP has_dyn_re_0SEXP, SEXP has_dyn_re_1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< int >::type n_trans_coef(n_trans_coefSEXP);
    Rcpp::traits::input_parameter< int >::type n_dyn_coef_0(n_dyn_coef_0SEXP);
    Rcpp::traits::input_parameter< int >::type n_dyn_coef_1(n_dyn_coef_1SEXP);
    Rcpp::traits::input_parameter< int >::type n_trans_re(n_trans_reSEXP);
    Rcpp::traits::input_parameter< int >::type n_dyn_re_0(n_dyn_re_0SEXP);
    Rcpp::traits::input_parameter< int >::type n_dyn_re_1(n_dyn_re_1SEXP);
    Rcpp::traits::input_parameter< bool >::type has_trans_re(has_trans_reSEXP);
    Rcpp::traits::input_parameter< bool >::type has_dyn_re_0(has_dyn_re_0SEXP);
    Rcpp::traits::input_parameter< bool >::type has_dyn_re_1(has_dyn_re_1SEXP);
    rcpp_result_gen = Rcpp::wrap(phase_log_prior_re(params, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, n_trans_re, n_dyn_re_0, n_dyn_re_1, has_trans_re, has_dyn_re_0, has_dyn_re_1));
    return rcpp_result_gen;
END_RCPP
}
// phase_log_posterior_re
double phase_log_posterior_re(NumericVector params, List data, int n_trans_coef, int n_dyn_coef_0, int n_dyn_coef_1, int n_trans_re, int n_dyn_re_0, int n_dyn_re_1, bool has_trans_re, bool has_dyn_re_0, bool has_dyn_re_1);
RcppExport SEXP _phaseR_phase_log_posterior_re(SEXP paramsSEXP, SEXP dataSEXP, SEXP n_trans_coefSEXP, SEXP n_dyn_coef_0SEXP, SEXP n_dyn_coef_1SEXP, SEXP n_trans_reSEXP, SEXP n_dyn_re_0SEXP, SEXP n_dyn_re_1SEXP, SEXP has_trans_reSEXP, SEXP has_dyn_re_0SEXP, SEXP has_dyn_re_1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type n_trans_coef(n_trans_coefSEXP);
    Rcpp::traits::input_parameter< int >::type n_dyn_coef_0(n_dyn_coef_0SEXP);
    Rcpp::traits::input_parameter< int >::type n_dyn_coef_1(n_dyn_coef_1SEXP);
    Rcpp::traits::input_parameter< int >::type n_trans_re(n_trans_reSEXP);
    Rcpp::traits::input_parameter< int >::type n_dyn_re_0(n_dyn_re_0SEXP);
    Rcpp::traits::input_parameter< int >::type n_dyn_re_1(n_dyn_re_1SEXP);
    Rcpp::traits::input_parameter< bool >::type has_trans_re(has_trans_reSEXP);
    Rcpp::traits::input_parameter< bool >::type has_dyn_re_0(has_dyn_re_0SEXP);
    Rcpp::traits::input_parameter< bool >::type has_dyn_re_1(has_dyn_re_1SEXP);
    rcpp_result_gen = Rcpp::wrap(phase_log_posterior_re(params, data, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, n_trans_re, n_dyn_re_0, n_dyn_re_1, has_trans_re, has_dyn_re_0, has_dyn_re_1));
    return rcpp_result_gen;
END_RCPP
}
// phase_log_likelihood_k
double phase_log_likelihood_k(NumericVector params, List data, IntegerVector n_dyn_coef, IntegerVector n_trans_coef, int k_phases);
RcppExport SEXP _phaseR_phase_log_likelihood_k(SEXP paramsSEXP, SEXP dataSEXP, SEXP n_dyn_coefSEXP, SEXP n_trans_coefSEXP, SEXP k_phasesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n_dyn_coef(n_dyn_coefSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n_trans_coef(n_trans_coefSEXP);
    Rcpp::traits::input_parameter< int >::type k_phases(k_phasesSEXP);
    rcpp_result_gen = Rcpp::wrap(phase_log_likelihood_k(params, data, n_dyn_coef, n_trans_coef, k_phases));
    return rcpp_result_gen;
END_RCPP
}
// phase_log_prior_k
double phase_log_prior_k(NumericVector params, IntegerVector n_dyn_coef, IntegerVector n_trans_coef, int k_phases);
RcppExport SEXP _phaseR_phase_log_prior_k(SEXP paramsSEXP, SEXP n_dyn_coefSEXP, SEXP n_trans_coefSEXP, SEXP k_phasesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n_dyn_coef(n_dyn_coefSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n_trans_coef(n_trans_coefSEXP);
    Rcpp::traits::input_parameter< int >::type k_phases(k_phasesSEXP);
    rcpp_result_gen = Rcpp::wrap(phase_log_prior_k(params, n_dyn_coef, n_trans_coef, k_phases));
    return rcpp_result_gen;
END_RCPP
}
// phase_log_posterior_k
double phase_log_posterior_k(NumericVector params, List data, IntegerVector n_dyn_coef, IntegerVector n_trans_coef, int k_phases);
RcppExport SEXP _phaseR_phase_log_posterior_k(SEXP paramsSEXP, SEXP dataSEXP, SEXP n_dyn_coefSEXP, SEXP n_trans_coefSEXP, SEXP k_phasesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n_dyn_coef(n_dyn_coefSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n_trans_coef(n_trans_coefSEXP);
    Rcpp::traits::input_parameter< int >::type k_phases(k_phasesSEXP);
    rcpp_result_gen = Rcpp::wrap(phase_log_posterior_k(params, data, n_dyn_coef, n_trans_coef, k_phases));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_phaseR_phaseR_nuts_sampler", (DL_FUNC) &_phaseR_phaseR_nuts_sampler, 9},
    {"_phaseR_phaseR_nuts_sampler_re", (DL_FUNC) &_phaseR_phaseR_nuts_sampler_re, 15},
    {"_phaseR_phaseR_nuts_sampler_k", (DL_FUNC) &_phaseR_phaseR_nuts_sampler_k, 9},
    {"_phaseR_phase_log_likelihood", (DL_FUNC) &_phaseR_phase_log_likelihood, 5},
    {"_phaseR_phase_log_prior", (DL_FUNC) &_phaseR_phase_log_prior, 4},
    {"_phaseR_phase_log_posterior", (DL_FUNC) &_phaseR_phase_log_posterior, 5},
    {"_phaseR_phase_log_likelihood_re", (DL_FUNC) &_phaseR_phase_log_likelihood_re, 11},
    {"_phaseR_phase_log_prior_re", (DL_FUNC) &_phaseR_phase_log_prior_re, 10},
    {"_phaseR_phase_log_posterior_re", (DL_FUNC) &_phaseR_phase_log_posterior_re, 11},
    {"_phaseR_phase_log_likelihood_k", (DL_FUNC) &_phaseR_phase_log_likelihood_k, 5},
    {"_phaseR_phase_log_prior_k", (DL_FUNC) &_phaseR_phase_log_prior_k, 4},
    {"_phaseR_phase_log_posterior_k", (DL_FUNC) &_phaseR_phase_log_posterior_k, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_phaseR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
