# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

phaseR_nuts_sampler <- function(data, init, n_iter, n_warmup, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, target_accept = 0.8, max_treedepth = 10L) {
    .Call(`_phaseR_phaseR_nuts_sampler`, data, init, n_iter, n_warmup, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, target_accept, max_treedepth)
}

phaseR_nuts_sampler_re <- function(data, init, n_iter, n_warmup, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, n_trans_re, n_dyn_re_0, n_dyn_re_1, has_trans_re, has_dyn_re_0, has_dyn_re_1, target_accept = 0.8, max_treedepth = 10L) {
    .Call(`_phaseR_phaseR_nuts_sampler_re`, data, init, n_iter, n_warmup, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, n_trans_re, n_dyn_re_0, n_dyn_re_1, has_trans_re, has_dyn_re_0, has_dyn_re_1, target_accept, max_treedepth)
}

phaseR_nuts_sampler_glm <- function(data, init, n_iter, n_warmup, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, family_0, family_1, n_trials_0, n_trials_1, target_accept = 0.8, max_treedepth = 10L) {
    .Call(`_phaseR_phaseR_nuts_sampler_glm`, data, init, n_iter, n_warmup, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, family_0, family_1, n_trials_0, n_trials_1, target_accept, max_treedepth)
}

phaseR_nuts_sampler_k <- function(data, init, n_iter, n_warmup, n_dyn_coef, n_trans_coef, k_phases, target_accept = 0.8, max_treedepth = 10L) {
    .Call(`_phaseR_phaseR_nuts_sampler_k`, data, init, n_iter, n_warmup, n_dyn_coef, n_trans_coef, k_phases, target_accept, max_treedepth)
}

phaseR_nuts_sampler_multi_re <- function(data, init, n_iter, n_warmup, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, trans_re_info, dyn_re_info_0, dyn_re_info_1, target_accept = 0.8, max_treedepth = 10L) {
    .Call(`_phaseR_phaseR_nuts_sampler_multi_re`, data, init, n_iter, n_warmup, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, trans_re_info, dyn_re_info_0, dyn_re_info_1, target_accept, max_treedepth)
}

phase_log_likelihood <- function(params, data, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1) {
    .Call(`_phaseR_phase_log_likelihood`, params, data, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1)
}

phase_log_prior <- function(params, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1) {
    .Call(`_phaseR_phase_log_prior`, params, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1)
}

phase_log_posterior <- function(params, data, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1) {
    .Call(`_phaseR_phase_log_posterior`, params, data, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1)
}

phase_log_likelihood_re <- function(params, data, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, n_trans_re, n_dyn_re_0, n_dyn_re_1, has_trans_re, has_dyn_re_0, has_dyn_re_1) {
    .Call(`_phaseR_phase_log_likelihood_re`, params, data, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, n_trans_re, n_dyn_re_0, n_dyn_re_1, has_trans_re, has_dyn_re_0, has_dyn_re_1)
}

phase_log_prior_re <- function(params, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, n_trans_re, n_dyn_re_0, n_dyn_re_1, has_trans_re, has_dyn_re_0, has_dyn_re_1) {
    .Call(`_phaseR_phase_log_prior_re`, params, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, n_trans_re, n_dyn_re_0, n_dyn_re_1, has_trans_re, has_dyn_re_0, has_dyn_re_1)
}

phase_log_posterior_re <- function(params, data, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, n_trans_re, n_dyn_re_0, n_dyn_re_1, has_trans_re, has_dyn_re_0, has_dyn_re_1) {
    .Call(`_phaseR_phase_log_posterior_re`, params, data, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, n_trans_re, n_dyn_re_0, n_dyn_re_1, has_trans_re, has_dyn_re_0, has_dyn_re_1)
}

phase_log_likelihood_glm <- function(params, data, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, family_0, family_1, n_trials_0, n_trials_1) {
    .Call(`_phaseR_phase_log_likelihood_glm`, params, data, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, family_0, family_1, n_trials_0, n_trials_1)
}

phase_log_prior_glm <- function(params, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, family_0, family_1) {
    .Call(`_phaseR_phase_log_prior_glm`, params, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, family_0, family_1)
}

phase_log_posterior_glm <- function(params, data, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, family_0, family_1, n_trials_0, n_trials_1) {
    .Call(`_phaseR_phase_log_posterior_glm`, params, data, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, family_0, family_1, n_trials_0, n_trials_1)
}

phase_log_likelihood_k <- function(params, data, n_dyn_coef, n_trans_coef, k_phases) {
    .Call(`_phaseR_phase_log_likelihood_k`, params, data, n_dyn_coef, n_trans_coef, k_phases)
}

phase_log_prior_k <- function(params, n_dyn_coef, n_trans_coef, k_phases) {
    .Call(`_phaseR_phase_log_prior_k`, params, n_dyn_coef, n_trans_coef, k_phases)
}

phase_log_posterior_k <- function(params, data, n_dyn_coef, n_trans_coef, k_phases) {
    .Call(`_phaseR_phase_log_posterior_k`, params, data, n_dyn_coef, n_trans_coef, k_phases)
}

phase_log_likelihood_multi_re <- function(params, data, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, trans_re_info, dyn_re_info_0, dyn_re_info_1) {
    .Call(`_phaseR_phase_log_likelihood_multi_re`, params, data, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, trans_re_info, dyn_re_info_0, dyn_re_info_1)
}

phase_log_prior_multi_re <- function(params, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, trans_re_info, dyn_re_info_0, dyn_re_info_1) {
    .Call(`_phaseR_phase_log_prior_multi_re`, params, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, trans_re_info, dyn_re_info_0, dyn_re_info_1)
}

phase_log_posterior_multi_re <- function(params, data, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, trans_re_info, dyn_re_info_0, dyn_re_info_1) {
    .Call(`_phaseR_phase_log_posterior_multi_re`, params, data, n_trans_coef, n_dyn_coef_0, n_dyn_coef_1, trans_re_info, dyn_re_info_0, dyn_re_info_1)
}

